### ISSUE TITLE
Do all those third parties actually work during tests?

### ISSUE THREAD

**Issue by erykpiast** [patrickhulce/third-party-web#115]
I wonder if you know the methodology of running tests or the environment setup: are those tracking scripts forced to work and actually track things? Many tools implement some kind of sampling rate and abort early when the server (or the script itself) decides that the session or page view shouldn't be tracked. In such a case, measured impact of the third party is much smaller in compare to scenario when the script collects a data. Simply attaching the script may not do much harm, but enabling it can change the performance definitely. So, how is it in this case?

**Comment by patrickhulce** [comment]
> are those tracking scripts forced to work and actually track things

No, in practice this isn't really possible in a generic way (not to mention it's far too easy to detect HTTPArchive and pull a [Volkswagen](https://en.wikipedia.org/wiki/Volkswagen_emissions_scandal) 😞 ).

> In such a case, measured impact of the third party is much smaller in compare to scenario when the script collects a data.

It sure is but not even for just the sampling reason, all of this is exclusively on a page load without interaction. Most of these third-parties will have even more significant impact once a user starts clicking around. Think of these numbers as the bare minimum level of impact.

**Comment by erykpiast** [comment]
Gotcha! Thanks for the answer :)
