### ISSUE TITLE
IAB CMPs are listed under AdRoll due to an error in the classification inside entities.js

### ISSUE THREAD

**Issue by HeinzBaumann** [patrickhulce/third-party-web#120]
We noticed that all IAB consent managers (multiple vendors supply these) are getting listed under AdRoll due to an error how their CMP domain is declared in entities.js. The domain should not be *.adroll.mgr.consensu.org but as adroll.mgr.consensu.org. We also like to update the Quantcast entry to include the our consent manager with the domain quantcast.mgr.consensu.org. Can we fix the Adroll entry to not use the asterix, which is wrong in this case. On mgr.consensu.org the subdomain is the CMP vendor name, there is no additional prefix. 
Suggested change is something like this:

```diff
index 4e8f746..dc61861 100644
--- a/data/entities.js
+++ b/data/entities.js
@@ -909,8 +909,8 @@ module.exports = [
     name: 'Adroll',
     homepage: 'https://www.adroll.com/',
     categories: ['ad'],
-    domains: ['*.adroll.com', '*.adroll.mgr.consensu.org'],
-    examples: ['d.adroll.com', 's.adroll.com', 'd.adroll.mgr.consensu.org'],
+    domains: ['*.adroll.com', 'adroll.mgr.consensu.org'],
+    examples: ['d.adroll.com', 's.adroll.com', 'adroll.mgr.consensu.org'],
   },
   {
     name: 'Twitch',
@@ -1450,19 +1450,21 @@ module.exports = [
   {
     name: 'Quantcast',
     homepage: 'https://www.quantcast.com',
-    categories: ['analytics'],
+    categories: ['analytics', 'utility'],
     domains: [
       '*.brtstats.com',
       '*.quantcount.com',
       '*.quantserve.com',
       '*.semantictec.com',
       '*.ntv.io',
+      'quantcast.mgr.consensu.org',
     ],
     examples: [
       'pixel.quantserve.com',
       'secure.quantserve.com',
       'cms.quantserve.com',
       'rules.quantcount.com',
+      'quantcast.mgr.consensu.org',
     ],
   },
   {
```
---
I also have a question whether can add a new category called 'ConsentManagers'? Currently the one that fits best is 'utility'. 

Thanks

**Comment by eligrey** [comment]
Consent managers should definitely get their own category at this point imo.

**Comment by patrickhulce** [comment]
thanks for filing @HeinzBaumann! great catch, yes we'll happily accept this fix (would you like to open a PR for it or prefer for us to take care of it?)

A new category for consent managers sounds good, they don't really belong as a subset of anything else at the moment and it's quite likely to grow moving forward :) 

cc @andydavies I believe you were just talking to me about this.

**Comment by andydavies** [comment]
Yes, it was someone at Quantcast who asked me why their CMP showed up as AdRoll in Lighthouse

I was planning on adding the other CMPs using the TCF 2 list on this page https://iabeurope.eu/cmp-list/

@HeinzBaumann Is there a list of non-IAB compliant CMPs anywhere, and also can you give me any pointers to CMPs for CCPA?

**Comment by HeinzBaumann** [comment]
@andydavies Unfortunately there is no list of non-IAB compliant or CCPA CMPs. Only IAB EU requires CMP for TCF (GDPR) to register. But many of these support CCPA as well. 
So can I leave this in your hands to pull the PR?

**Comment by andydavies** [comment]
@HeinzBaumann @patrickhulce #121 resolves this
