### ISSUE TITLE
Add category for performance analytics tool?

### ISSUE THREAD

**Issue by soulgalore** [patrickhulce/third-party-web#13]
Hi @patrickhulce , I wanna add a couple performance analytics tools: Akamais mpulse, Speedcurvces Lux and Pingdoms. I can do PRs tonight but I'm thinking about a good category? Do you have a good name?

Best
Peter

**Comment by patrickhulce** [comment]
IMO, these should probably go under the pre-existing analytics bucket. While they track user actions and visits for a different purpose, they're still fundamentally tracking page behavior for analysis :)

Thanks for all the additions by the way!! :D

**Comment by soulgalore** [comment]
Pushed them to the analytics bucket.
