### ISSUE TITLE
Add category for Consent Management Platform

### ISSUE THREAD

**Issue by motiko** [patrickhulce/third-party-web#130]
They tend to be heavy and influence LCP in most cases.
Some examples:
OneTrust
CookieHub
usercentrics

WDYT?
Would be happy to help with a PR in case you find it useful.

**Comment by patrickhulce** [comment]
Thanks for filing @motiko! Yes I've been meaning to do this recategorization to capture CMPs for a while now, just haven't gotten the time lately. 

PR would be welcome :)

**Comment by coliff** [comment]
Can this issue be closed now that this category is there?

https://github.com/patrickhulce/third-party-web#consent-provider

**Comment by patrickhulce** [comment]
yep thanks @coliff! 👍
