### ISSUE TITLE
www/ toolchain is out-of-date

### ISSUE THREAD

**Issue by christobill** [patrickhulce/third-party-web#135]
Seems that the UI is broken when building in local, the navbar overlaps with the D3 Treemap:

![broken-third-party-web-ui-localhost](https://user-images.githubusercontent.com/7570009/124289621-d0b11700-db52-11eb-931e-1c0a105de0fe.png)

Browser: `Chrome 91.0.4472.114`
Node version: `node v14.17.1 (npm v6.14.13)`

**Comment by patrickhulce** [comment]
Thanks for filing @christobill! The toolchain is a little old I'm only able to get the project to build successfully with node 10.x

#128 intended to upgrade us but I think is stuck with a few other bugs at the moment.

**Comment by christobill** [comment]
Hello @patrickhulce ! Thanks for your answer
I succeeded to update the toolchain for `www/` to `node 14.x` :tada: 

See the following PR: https://github.com/patrickhulce/third-party-web/pull/138 :pray:
