### ISSUE TITLE
Rewrite origin-query.generated.sql and entity-per-page.generated.sql for cost and time reasons

### ISSUE THREAD

**Issue by christobill** [patrickhulce/third-party-web#142]
Hello :wave: 

Would you consider to rewrite the `origin-query.generated.sql` and `entity-per-page.generated.sql`?

### The idea:

Instead of looping 35 times to generate the requests: https://github.com/patrickhulce/third-party-web/blob/06b3c5e4e41563ce66b2c299a7f2f1bb53a69cad/bin/generate-sql.js#L12
We could use `BigQuery` `UNNEST` function

### Advantages:

1. Much more efficient queries,
Orignal `origin-query.generated.sql` query:
![origin-query-generated](https://user-images.githubusercontent.com/7570009/127902287-f7d9d382-adcf-4bbd-840f-0377e4aaeb46.png)

Compared with using `BigQuery` `UNNEST`:
![origin-query-rewritten](https://user-images.githubusercontent.com/7570009/127902417-8b2fb35f-f191-45f3-9f83-04cb8f640562.png)

Elapsed time
   28 min 56 sec **vs** 14.9 sec 

Slot time consumed
   35 days 14 hr **vs**  5 hr 14 min
 
Bytes shuffled
    795.77 MB **vs** 102.81 MB

 => a much faster and cheaper query
 
 2. Get the complete data
 Looping 35 times to get `item[34]` can miss data on `item[x]` for x > 34
 With `BigQuery` `UNNEST`, we get all the data
 
 3. Less steps to update the data and less maintaining
 We won't need to generated these two queries anymore
 So we can remove the corresponding code :smile:  
 
 @patrickhulce What do you think?
 
See linked PR

**Comment by patrickhulce** [comment]
thanks @christobill! yep, I love it! I did this as well for the web almanac project but just never ported the queries back here, so completely agree 👍

**Comment by christobill** [comment]
https://github.com/patrickhulce/third-party-web/pull/143 has been merged, I am closing this ticket

Thank you!
