### ISSUE TITLE
Refresh the data of third party web

### ISSUE THREAD

**Issue by christobill** [patrickhulce/third-party-web#162]
Hello @patrickhulce !

If I am correct, the data hasn't been refreshed for a while :thinking: 
July 2021 seems to be the last update of the data

I am preparing a PR with refreshed data,, if that is ok for you?

**Comment by patrickhulce** [comment]
Awesome thanks a million @christobill!

**Comment by patrickhulce** [comment]
@christobill thanks so much for the refresh data example! I took a whack at writing an automated script to make this easier in the future, I double checked the results with your PR and things look good 🎉 thanks for your help! :D

**Comment by patrickhulce** [comment]
fixed by #163 and b97f6fcb24de3181cfe5352d246024dbd5a7820e 🎉
