### ISSUE TITLE
Migrate /www to typescript

### ISSUE THREAD

**Issue by christobill** [patrickhulce/third-party-web#164]
Hello @patrickhulce !

What would you think about migrating `/www` to `typescript`?

I am preparing an PR in case you are interested :smile:

**Comment by patrickhulce** [comment]
Love it! Beyond that I was actually thinking of doing a bigger rewrite to try out remix here + add better routing and entity data with network request not just script info. Happy for you to do whatever you like to it though :)

**Comment by patrickhulce** [comment]
fixed by #165 🎉
