### ISSUE TITLE
Security: Polyfill Supplay Chain Attack

### ISSUE THREAD

**Issue by and-who** [patrickhulce/third-party-web#220]
Currently there is an active Security Issue:
https://sansec.io/research/polyfill-supply-chain-attack

Which warns about the usage of 'cdn.polyfill.io', which is used by this Project

**Comment by starsinmypockets** [comment]
+1

**Comment by patrickhulce** [comment]
Thanks for filing! 

Can you point me more directly to where we're using polyfill.io? I'm not aware of any _usage_, just data on which sites _are_ using it, which is more valuable now than ever :)

**Comment by patrickhulce** [comment]
Can anyone share how they're being alerted to this? We don't use polyfill.io or load anything from it at all. I assume people are grepping for `polyfill.io`, seeing the text in the package assets, and alarm bells are going off without any nuance, but is there more? Are we being erroneously flagged by some other automated system?

> how polyfill.io data is retrieved and stored in this project?

We're not retrieving or storing anything from polyfill.io. We query HTTPArchive for how many sites make requests to the polyfill.io domain. [See README](https://github.com/patrickhulce/third-party-web?tab=readme-ov-file#methodology).

> This project is being used by the lighthouse. I want to understand if this causes any security risk.

Certainly not from the polyfill.io asset loading vulnerabilities.

I'm going to be closing this as not an issue.

**Comment by KratosGemini** [comment]
> Can anyone share how they're being alerted to this?

> I assume people are grepping for polyfill.io, seeing the text in the package assets....

I can say this is how I came across this. As this package is a dependency of a dependency, I didn't have any familiarity with what this package does. So I came here to look for any report of the issue. I found this and watched it, but apparently it's a false positive. Thanks for the clarification.
