### ISSUE TITLE
Invalid grant / bigquery gcloud auth

### ISSUE THREAD

**Issue by paulirish** [patrickhulce/third-party-web#227]
I'm trying to get authenticated to update the bigquery but running into some challenges.

Readme indicates using gcp-credentials but that filename isn't supported anymore. But.. even then.. I'm not sure this approach is preferred.

@Nigui @kporal  what approach did yall use most recently?

I'm getting the farthest by creating a new KEY with my service account.. downloading that json. then

```sh
GOOGLE_APPLICATION_CREDENTIALS=thatseviceaccountkeyfile.json  node bin/automated-update.js
```

But still facing some permission challenges. I want to figure out the supported path so we can update the documentation.

**Comment by patrickhulce** [comment]
Thanks Paul :) 

The `GOOGLE_APPLICATION_CREDENTIALS` path you've noted should work. We don't do anything fancy here with auth, just invoke the GCloud SDK which looks for [default creds](https://cloud.google.com/docs/authentication/application-default-credentials).

What permissions errors are you getting? Authentication? Query authorization? Write authorization?

**Comment by paulirish** [comment]
Was getting invalid grant. mostly fixed with the env variable as i noted.. now i'm at 

<img width="963" alt="image" src="https://github.com/user-attachments/assets/343d66b7-1ad8-4b90-b9df-c1520945a101">

this seems to be related to #224

**Comment by patrickhulce** [comment]
Ah, I haven't fully run through with #224 yet, could have broken the pipeline :/

**Comment by Nigui** [comment]
Hello, sorry for the late answer. 
Did you found a fix for this "empty schema" issue yet? If not, I'll have a look and come back with it. 
Sorry again for that break.

**Comment by paulirish** [comment]
> Did you found a fix for this "empty schema" issue yet?

I haven't found a fix no. I was running with the original lighthouse-infrastructure GCP project fwiw.

> Sorry again for that break.

All good.  :)
