### ISSUE TITLE
Crazy Egg and Hello Bar  - two separate companies

### ISSUE THREAD

**Issue by imtall** [patrickhulce/third-party-web#231]
As CTO of Crazy Egg I recently discovered this project and love it. It's a great unbiased way for site owners to look at the impact of third-party scripts and to push the makers of third-party scripts (like us) to provide better performance. Thanks for your efforts!

While we'll be looking at improving our own performance I did notice that in `data/entities.js` there are some inaccuracies for Crazy Egg. There are some very old domains that we did in use in the distant past but no longer use (namely `cetrk.com` and `dnn506yrbagrg.cloudfront.net`). Anyone sites using those domains should update their installation and this may give inaccurate performance information for Crazy Egg. More importantly I noticed that Hello Bar, which is a completely separate company from Crazy Egg, was lumped in with Crazy Egg. It should read:

```
  {
    name: 'Crazy Egg',
    homepage: 'https://www.crazyegg.com/',
    category: 'analytics',
    domains: ['*.crazyegg.com'],
  },
  {
    name: 'Hello Bar',
    homepage: 'https://www.hellobar.com/',
    category: 'marketing',
    domains: ['*.hellobar.com'],
  },
```

Thanks for updating this when you get a chance!

**Comment by patrickhulce** [comment]
Thanks for the catching this @imtall ! We'll push an update shortly :)

**Comment by imtall** [comment]
Awesome, thank you!
