### ISSUE TITLE
Add Piwik/Matomo entity

### ISSUE THREAD

**Issue by WuglyakBolgoink** [patrickhulce/third-party-web#48]

**Comment by patrickhulce** [comment]
Could you be more specific? I'm not sure I understand your question :)

**Comment by rockeynebhwani** [comment]
@patrickhulce  - My guess is that this was just ask to add Piwik/Matomo to the list of 3rd parties.. 

https://matomo.org/
https://matomo.org/blog/2018/01/piwik-is-now-matomo/

**Comment by patrickhulce** [comment]
Ah thanks for the explanation @rockeynebhwani that would make sense :)

**Comment by mikkeschiren** [comment]
Did a small pull request for this
