### ISSUE TITLE
BootstrapCDN

### ISSUE THREAD

**Issue by XhmikosR** [patrickhulce/third-party-web#5]
Hey, @patrickhulce. We have switched to `stackpath.bootstrapcdn.com` almost a year ago. The old `maxcdn.bootstrapcdn.com` still works but we don't expose it in our frontend.

Also, `cdn.bootcss.com` isn't in any of our official hostnames. Not sure where you got it from.

**Comment by XhmikosR** [comment]
FYI, jQuery is using the same CDN infrastructure we use, StackPath.

**Comment by patrickhulce** [comment]
Ah that's why it dropped then! Thanks @XhmikosR!
