### ISSUE TITLE
The domain b-cdn.net is incorrectly classified as Sumo

### ISSUE THREAD

**Issue by DejanPelzel** [patrickhulce/third-party-web#66]
Hello,

We run a CDN service called BunnyCDN that uses b-cdn.net as a shared domain for tens of thousands of zones. After our users brought this to our attention we noticed that entities.json5 incorrectly links up our domain as Sumo, which is then showing up in PageSpeed Insights to everyone using it creating some fear and confusion.

```
{
    "name": "Sumo",
    "homepage": "https://sumo.com/",
    "categories": ["marketing"],
    "domains": ["*.sumo.com", "*.sumome.com", "*.b-cdn.net"],
    "examples": ["sumo.b-cdn.net", "load.sumo.com", "load.sumome.com"]
  },
```
Sumo only uses a small set of domains for example sumo.b-cdn.net so using *.b-cdn.net for the detection is incorrect. Is there a chance this could be improved?

Thanks!

**Comment by patrickhulce** [comment]
Thanks for the issue! Yep `*.b-cdn.net` can be replaced with just `sumo.b-cdn.net` and removed from examples. Interested in a PR? I'm currently on vacay with limited access :)

**Comment by DejanPelzel** [comment]
Done :)
