### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by soulgalore** [patrickhulce/third-party-web#7]
Hi @patrickhulce thanks for the great work! One of my projects has been to categorise 3rd-parties for Swedish government sites but I never got around, and third-party-web will make it so much easier for me.

But I miss a license, any chance you can add it? Then I can probably integrate it to other projects too. 

Thanks
Peter

**Comment by patrickhulce** [comment]
Ah thanks for filing I forgot to add one before I published! I'll add it tonight :)

**Comment by patrickhulce** [comment]
closed by 4072a7045cd0dfb7fe6b407fa78395cb93e9d4cf
