### ISSUE TITLE
Include ClickGuardian

### ISSUE THREAD

**Issue by braders** [patrickhulce/third-party-web#71]
I propose the addition of [ClickGuardian](https://clickguardian.co.uk/). This is a platform which can have  a significant negative impact on performance, due to it's fingerprinting of users.

For all new sign-ups it uses v2.clickguardian.app to host all it's assets. (If we add this, we should probably try to track down the v1 domain as well...)

**Comment by patrickhulce** [comment]
Sounds good @braders interested in contributing the PR? :)

**Comment by braders** [comment]
I've had a look and the v1 of the service uses protection.clickguardian.co.uk for all assets.

I'll take a look at creating a PR in the next few days.
