### ISSUE TITLE
Fails to parse cluster domains.

### ISSUE THREAD

**Issue by einaralex** [patrickhulce/third-party-web#87]
I'm running sitespeedio in a cluster, when running it against internal domains (which look like this: `http://www-my-domain-master`) I get an error from third-party-web.

```
ERROR: Error: Unable to find domain in "www-my-domain-master"
    at getDomainFromOriginOrURL (/usr/src/app/node_modules/third-party-web/lib/create-entity-finder-api.js:8:9)
    at getEntityInDataset (/usr/src/app/node_modules/third-party-web/lib/create-entity-finder-api.js:18:18)
   ...
```

**Comment by patrickhulce** [comment]
Thanks for filing @einaralex! I have an alternative, but I'm curious what your expectation is for the behavior here and then for strings that aren't valid URLs?

**Comment by einaralex** [comment]
Hmm good point, not sure actually, can I specify what my valid URLs are?

**Comment by patrickhulce** [comment]
> can I specify what my valid URLs are?

that's an interesting idea! basically giving control over whether an error is thrown we'll do something along those lines

**Comment by patrickhulce** [comment]
We decided against validation altogether and now just return `undefined` when a URL is invalid

**Comment by einaralex** [comment]
Works for me, just tried it out. Thank you so much!
