### ISSUE TITLE
Incorrect detect of Yandex Share

### ISSUE THREAD

**Issue by hcodes** [patrickhulce/third-party-web#88]
Domain https://yastatic.net is CDN and used for statics of hundreds of Yandex services.

Yandex Share is one of the Yandex services and has a single script - https://yastatic.net/share2/share.js

Not Yandex Share:
- https://yastatic.net/s3/mapsapi-jslibs/heatmap/0.0.1/heatmap.min.js
- https://yastatic.net/jquery/2.1.4/jquery.min.js
- https://yastatic.net/lodash/4.17.11/lodash.min.js
- https://yastatic.net/bem-core/latest/touch/bem-core.js
- https://yastatic.net/s3/mapsapi-jslibs/polylabeler/1.0.2/polylabel.min.js 
- and 100,000 more

**Comment by hcodes** [comment]
Lighthouse uses this package and its report contains incorrect information. My site does not use Yandex Share, but other Yandex scripts are enabled.
<img width="681" alt="изображение" src="https://user-images.githubusercontent.com/157520/83818778-d8dd1f80-a6d0-11ea-9b5e-3dba07e59353.png">

**Comment by patrickhulce** [comment]
Thanks for the example @hcodes!

**Comment by hcodes** [comment]
👍
