### ISSUE TITLE
Call for subject matter experts to contribute to the web almanac

### ISSUE THREAD

**Issue by patrickhulce** [patrickhulce/third-party-web#99]
Hey everyone 👋 

The [web almanac](https://almanac.httparchive.org/en/2019/) is going to be kicking off soon for 2020 and is looking for authors on a chapter about third parties. I wrote [the chapter last year](https://almanac.httparchive.org/en/2019/third-parties) and wanted to open it up to contributors here who might have an interest in sharing their perspective on the topic. 

Open to anyone passionate about the effects of third party code on the web today :) Feel free to comment here or [DM](https://twitter.com/patrickhulce)/email if you'd prefer.

**Comment by patrickhulce** [comment]
@simonhearne 
@zeman 
@soulgalore 
@rockeynebhwani
@roystron85
@diagramatics
@c-torres

any interest or suggestions for nominations of someone in your network who might be able to share a unique perspective?

**Comment by simonhearne** [comment]
@patrickhulce I'd be happy to contribute this year 👍

**Comment by patrickhulce** [comment]
Solved thanks again @simonhearne  :)
